---
title: "Food Deserts in Virginia?"
output: html_document
bibliography: 
abstract: We examine the existence of food deserts in Virginia at the county level from 2011 to 2015, and find little evidence that access to healthy food influences health outcomes like obesity and diabetes.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Food deserts (FDs) are often defined as urban areas with extremely limited or no access to healthy food options; affordability is also a relevant defining characteristic.^[The idea of FDs developed in the United Kingdom to describe the lack of food shopping for residents near newly-built, isolated public housing units (New York Law School Racial Justice Project, 2012).] Walker et al. (2010) reviews the literature on food deserts and show that most scholars define food deserts in terms of access to healthy foods, the racial component of food deserts (i.e., that most food deserts are within predominantly black neighborhoods), the income gradient (i.e., most food deserts are within poorer neighborhoods), and that most food retailers in food deserts are non-chain stores and typically charge higher prices. 

When people live in food deserts, evidence suggests they are more likely to have poor diets and are more likely to be obese. This is especially when ‘mom and pop’ convenience stores and liquor stores are the primary food retailers. See, for example, “Life in a ‘Food Desert’” (Whelan et al., 2002) on FDs in London; and "Beyond the Food Desert” (Battersby, 2016) on food insecurity in South Africa). Weatherspoon, et al. (2012) measures the price elasticity of fruit in food deserts, which suggests consumers are price sensitive and suggest policies to lower prices, e.g., encourage competition. In efforts to eliminate food deserts, public health advocates and policymakers allocate public monies to encourage grocery stores to relocate, and they build farmers markets and virtual grocery stores. 

However, the metaphor of a food desert and even its existence depends on its definition and interpretation (Caspi, et al., 2012). For example, the US government defines the problem in terms of the lack of access to healthy foods, which they define as a town with at least 500 people who live over a mile from a supermarket. What is considered healthy food; what does access mean; what is the relevant size of a neighborhood, etc.? Bitler and Haider (2010) develop an economic approach to food deserts and also express similar concerns. Indeed, are food deserts such a burden when people can acquire food near their homes, at work, at schools, etc. (Bitler and Haider, 2010). Widener (2018) suggests the metaphor over emphasizes distance to supermarkets as a causal factor on health outcomes and should be retired. Indeed, Dubowitz et al. (2015), in “Healthy Food Access for Urban Food Desert Residents” and Dubowitz  et al. (2014) show that mere distance to healthy food options does not necessarily influence eating habits, especially in the context of two urban, african american communities in Pittsburgh. That is, while there were no supermarkets with healthy options in those neighborhoods, people traveled outside their neighborhoods to shop. Black and Macinko (2008) review the literature and find no consistent evdience on the relationship between access to healthy foods and obesity. Lee (2012) suggests that access to health or unhealthy food does not influence childhood obesity. 

In light of these arguments, we analyze the relationship between access to healthy food and health outcomes like obesity and diabetes across counties in the state of Virginia between 2011 and 2015. Advocates of the food desert concept postulate access has a negative effect on these health outcomes. However, we find no relationship between these two variables after accounting for median household income, access to recreational facilities, etc. Our results support earlier studies that show food deserts are not as burdensome as advocates and policymakers make them out to be. This is especially because, in VA, people have access to supermarkets within and without their counties. At the same time, while we find no relationship between access and obesity at the county level, this does not preclude the existence of food deserts. They might still exist within a neighborhood, but our results challenge naive conclusions regarding food deserts and negative health outcomes like obesity.

# Data and Methods

# Results

# Discussion and Conclusion

Our results suggest arguments related to food deserts are overstated. That is, there is no statistical relationship between access to healthy foods and adverse health outcomes like obesity and diabetes. One reason for these results might simply be that while people live in counties with less access to healthy foods, they adjust their shopping habits to acquire their desired food bundle. To the extent there are widely-used substitutes for healthy eating that are not measured with our measures of grocery stores, e.g., cross-county shopping, delivery services, people might still be able to maintain a healthy lifestyle, they can avoid obesity and diabetes, regardless of whether there is a food desert. At the same time, such substitutes might be lacking, which limits general conclusions. 

Our data from Virginia covers counties with various demographic characteristics; while we suggest these results are not biased by being from Virginia, we do not show this. In future research we plan to extend our model to other states, e.g., states with different levels of median income, demographics, and institutions to examine the validity of our model. For example, a comparison of our results in Virginia with results from other southern states might make the argument stronger. 