---
title: "Food Deserts"
author: "Carilli"
date: "3/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(plm)
library(broom)
library(jtools)
library(AER)
```

```{r}
food_desert <- read_csv("colorectal_data.csv") %>%
  mutate(median_household_income = median_household_income / 1000)

```

## EDA

```{r}
food_desert %>% 
  select(county, population, pop_over_65) %>% 
  arrange(desc(population))
```


```{r}
food_desert %>% 
  ggplot(aes(x = physical_inactivity, y = diabetes, color = (population > 100000))) +
  geom_point(na.rm = TRUE, alpha = 0.4)
```

```{r}
food_desert %>% 
  group_by(year) %>% 
  summarize(max(access_to_healthy_foods, na.rm = TRUE),
            min(access_to_healthy_foods, na.rm = TRUE),
            median(access_to_healthy_foods, na.rm = TRUE))
  # ggplot(aes(x = access_to_healthy_foods)) + 
  # geom_histogram() + 
  # facet_grid(~ year)
 
```


```{r}
food_desert %>% 
  # filter(year > 2012) %>% 
  ggplot(aes(x = adult_obesity)) +
  geom_histogram() + 
  facet_grid(~year)
```

```{r}
food_desert %>% 
  # filter(year > 2012) %>% 
  ggplot(aes(y = adult_obesity, group = year, x  = year)) + 
  geom_boxplot()

food_desert %>% 
  group_by(year) %>% 
  summarize(median(adult_obesity))
```

```{r}
all.equal(
food_desert %>% 
  filter(year == 2012) %>% 
  select(adult_obesity) 
,
food_desert %>% 
  filter(year == 2013) %>% 
  select(adult_obesity)
)
```



## Diabetes


```{r, diabetes}
food_desert %>% 
  filter(year > 2011) %>% 
  plm(diabetes ~ physical_inactivity + 
        pop_over_65 + median_household_income + access_to_healthy_foods +
        access_to_recreational_facilities + adult_smoking + excessive_drinking + adult_obesity + 
        factor(county), index = "county", model = "within", effect = "twoways", .) %>% 
  summary()
```

## Obesity

You can also embed plots, for example:

```{r obesity}
food_desert %>% 
  filter(year > 2011) %>% 
  plm(adult_obesity ~ physical_inactivity + 
        pop_over_65 + median_household_income + access_to_healthy_foods +
        access_to_recreational_facilities + adult_smoking + excessive_drinking + 
        factor(year), index = "county", model = "within", effect = "twoways", .) %>% 
  # fixef() %>% 
  summary()
```

```{r, diabetes_18_65}
food_desert %>% 
  filter(year > 2011) %>%
  plm(diabetes ~ physical_inactivity + 
        pop_between_18_and_65 + median_household_income + access_to_healthy_foods +
        access_to_recreational_facilities + adult_smoking + excessive_drinking + adult_obesity + 
        factor(county), index = "county", model = "within", effect = "twoways", .) %>% 
  summary()
```

```{r, diabetes_under_18}
food_desert %>% 
  filter(year > 2011) %>%
  plm(diabetes ~ physical_inactivity + 
        pop_under_18 + median_household_income + access_to_healthy_foods +
        access_to_recreational_facilities + adult_smoking + excessive_drinking + adult_obesity + 
        factor(county), index = "county", model = "within", effect = "twoways", .) %>% 
  summary()
```

```{r iv}
food_desert %>%
  filter(year > 2011) %>%
  plm(
    diabetes ~ access_to_healthy_foods + adult_obesity |
    physical_inactivity + access_to_healthy_foods +
    pop_over_65 + median_household_income +
    access_to_recreational_facilities + adult_smoking + excessive_drinking,
    index = "county",
    model = "within",
    effect = "twoways",
    .
  ) %>%
  summary()
```

```{r}
food_desert %>%
  filter(year > 2011) %>%
  lm(
    adult_obesity ~ physical_inactivity +
      pop_over_65 + median_household_income + access_to_healthy_foods +
      access_to_recreational_facilities + adult_smoking + excessive_drinking,
    .
  ) %>%
  summary()
```


# equations

$$
\begin{align}
\mathit{Health Outcome_{i,t}} = \beta_0 
&+ \beta_1\mathit{Healthy Food Access}_{i,t} 
+ \beta_2\mathit{AdultObesity}_{i,t} \\
&+ \beta_3\mathit{PhysicalInactivity_{i,t}} 
+ \beta_4\mathit{PopOver65_{i,t}}  \\
&+ \beta_5\mathit{MedianHouseholdIncome_{i,t}} 
+ \beta_6\mathit{AccessRecreationalFacilities_{i,t}}\\
&+ \beta_7\mathit{AdultSmokers_{i,t}}
+ \beta_8\mathit{ExcessiveDrinking_{i,t}}
+ \epsilon_{i,t}
\end{align}
$$